### PR TITLE
Add dup domain hook

### PR DESCRIPTION
**Pull request by ionrock**
This sorts out creating the right requirements.txt for CI to build a
deb. It also corrupts the requirements.txt so we should make sure we git
reset --HARD the repo (which we probably do anyway) before doing the
needful.

I'm thinking about sending a PR to dh-virtualenv as well to allow a
--requirements-file so that you could just add a flag that points to the
requirements file you want to use rather than assume requirements.txt.

I'd say do the same thing for pbr, but I can only imagine the pain that
would be...

### CODE REVIEW

**Comment by ionrock** [comment]
FYI, had to rebase.

**Comment by TimSimmons** [comment]
These commits should probably get squashed, no?

**Comment by filler** [comment]
Can you squash this?  Thx!

**Comment by ionrock** [comment]
@filler Sqaushed!

**Comment by filler** [comment]
:+1: lgtm

**Pull request merged**
